"""
Arena.ai bridge client.
- POST https://arena.ai/nextjs-api/stream/create-evaluation
- mode = "direct-battle"
- content-type: text/plain;charset=UTF-8
- Response stream: a0:"text"  ad:{"finishReason":"stop"}
- reCAPTCHA token generated by Tampermonkey userscript
"""
import asyncio
import logging
import time
import uuid as uuid_mod
from typing import AsyncGenerator, Optional

logger = logging.getLogger(__name__)

ARENA_BASE = "https://arena.ai"
STREAM_URL = f"{ARENA_BASE}/nextjs-api/stream/create-evaluation"

# ── Confirmed UUIDs from real network captures ─────────────────────────────
SLUG_TO_UUID: dict = {
    "claude-opus-4-5-20251101": "019adbec-8396-71cc-87d5-b47f8431a6a6",
    "claude-opus-4-6":          "019c2fac-13de-7550-a751-f5f593c77c72",
    "gpt-5.3-codex":            "019cc0bf-aeb3-7a0f-9982-dab440effef3",
}

SLUG_TO_MODALITY: dict = {
    "gpt-5.3-codex": "webdev",
}

_runtime_uuid_map: dict = {}


# ── UUIDv7 generator ───────────────────────────────────────────────────────
def _make_uuid7() -> str:
    ms     = int(time.time() * 1000)
    rand_a = uuid_mod.uuid4().int & 0xFFF
    rand_b = uuid_mod.uuid4().int & 0x3FFFFFFFFFFFFFFF
    hi = (ms << 16) | (0x7 << 12) | rand_a
    lo = (0b10 << 62) | rand_b
    h  = f"{hi:016x}{lo:016x}"
    return f"{h[0:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"


# ── Token rotator ──────────────────────────────────────────────────────────
class TokenEntry:
    def __init__(self, token_v1_0: str, token_v1_1: str = ""):
        self.token_v1_0 = token_v1_0
        self.token_v1_1 = token_v1_1


class TokenRotator:
    def __init__(self):
        self._entries: list[TokenEntry] = []
        self._idx = 0

    def set_tokens(self, entries: list[TokenEntry]):
        self._entries = entries
        self._idx = 0

    def next(self) -> Optional[TokenEntry]:
        if not self._entries:
            return None
        e = self._entries[self._idx % len(self._entries)]
        self._idx += 1
        return e

    @property
    def count(self) -> int:
        return len(self._entries)


token_rotator = TokenRotator()


# ── Model list ─────────────────────────────────────────────────────────────
STATIC_MODELS = [
    ("claude-opus-4-6",            "anthropic"),
    ("claude-opus-4-5-20251101",   "anthropic"),
    ("claude-sonnet-4-5-20251101", "anthropic"),
    ("claude-haiku-3-5-20241022",  "anthropic"),
    ("claude-opus-4-20250514",     "anthropic"),
    ("claude-sonnet-4-20250514",   "anthropic"),
    ("claude-3-7-sonnet-20250219", "anthropic"),
    ("claude-3-5-sonnet-20241022", "anthropic"),
    ("gpt-5.3-codex",              "openai"),
    ("gpt-4o",                     "openai"),
    ("gpt-4o-mini",                "openai"),
    ("gpt-4-turbo",                "openai"),
    ("o3",                         "openai"),
    ("o4-mini",                    "openai"),
    ("o3-mini",                    "openai"),
    ("o1",                         "openai"),
    ("gemini-2.5-pro-preview",     "google"),
    ("gemini-2.5-flash-preview",   "google"),
    ("gemini-2.0-flash",           "google"),
    ("gemini-2.0-pro",             "google"),
    ("gemini-1.5-pro",             "google"),
    ("llama-3.3-70b-instruct",     "meta"),
    ("llama-4-scout",              "meta"),
    ("llama-4-maverick",           "meta"),
    ("deepseek-r1",                "deepseek"),
    ("deepseek-v3",                "deepseek"),
    ("grok-3",                     "xai"),
    ("grok-3-mini",                "xai"),
    ("mistral-large-2411",         "mistral"),
    ("mistral-medium-3",           "mistral"),
    ("qwen-2.5-72b-instruct",      "alibaba"),
    ("qwen-3-235b",                "alibaba"),
    ("gemma-3-27b-it",             "google"),
    ("command-r-plus-08-2024",     "cohere"),
]


def get_models_list() -> list[dict]:
    ts = int(time.time())
    return [
        {"id": slug, "object": "model", "created": ts, "owned_by": owner}
        for slug, owner in STATIC_MODELS
    ]


def resolve_model_uuid(slug: str) -> str:
    if slug in _runtime_uuid_map:
        return _runtime_uuid_map[slug]
    if slug in SLUG_TO_UUID:
        return SLUG_TO_UUID[slug]
    logger.warning(f"⚠️  No UUID for '{slug}' — sending slug (will likely 500)")
    return slug


def get_modality(slug: str) -> str:
    return SLUG_TO_MODALITY.get(slug, "chat")


# ── Content builder — includes full conversation history ────────────────────
def _build_content(messages: list[dict]) -> str:
    """
    Build the content string to send to Arena.
    Includes full conversation history so Arena has context,
    even though we create a new session each time.
    """
    if not messages:
        return ""

    # Filter out empty messages
    valid = [m for m in messages if m.get("content", "").strip()]

    if not valid:
        return ""

    # Only one message — just send it directly
    if len(valid) == 1:
        return valid[0]["content"].strip()

    # Multiple messages — build conversation history
    # All messages except the last form the history
    history = valid[:-1]
    current = valid[-1]

    parts = ["[Previous conversation]"]
    for m in history:
        role = m.get("role", "user").capitalize()
        content = m["content"].strip()
        parts.append(f"{role}: {content}")

    parts.append("")
    parts.append("[Current message]")
    parts.append(current["content"].strip())

    return "\n".join(parts)


# ── Payload builder ────────────────────────────────────────────────────────
def build_payload(model_slug: str, messages: list[dict], recaptcha_token: str) -> dict:
    session_id       = _make_uuid7()
    user_msg_id      = _make_uuid7()
    model_a_msg_id   = _make_uuid7()

    model_uuid = resolve_model_uuid(model_slug)
    modality   = get_modality(model_slug)
    content    = _build_content(messages)

    logger.info(f"🔑 UUID: {model_slug} → {model_uuid}")

    return {
        "id":              session_id,
        "mode":            "direct-battle",
        "modelAId":        model_uuid,
        "userMessageId":   user_msg_id,
        "modelAMessageId": model_a_msg_id,
        "userMessage": {
            "content":                  content,
            "experimental_attachments": [],
            "metadata":                 {},
        },
        "modality":        modality,
        "recaptchaV3Token": recaptcha_token,
    }


# ── Arena client ───────────────────────────────────────────────────────────
class ArenaClient:
    def __init__(self):
        self._page = None
        self._browser = None
        self._model_uuid_map: dict = {}
        self._models_raw: list = []

    async def start(self):
        try:
            from camoufox.async_api import AsyncCamoufox
            logger.info("🦊 Launching Camoufox...")
            self._browser_ctx = AsyncCamoufox(headless=True, block_images=True)
            browser = await self._browser_ctx.__aenter__()
            self._page = await browser.new_page()
            logger.info("✅ Camoufox browser ready")
        except Exception as e:
            logger.warning(f"⚠️ Camoufox failed to start: {e}")
            self._page = None

    async def stop(self):
        try:
            if self._browser_ctx:
                await self._browser_ctx.__aexit__(None, None, None)
        except Exception:
            pass

    async def stream_chat(
        self,
        model_slug: str,
        messages: list[dict],
        conv_fingerprint: str = "",
    ) -> AsyncGenerator[str, None]:
        from . import userscript_server as us

        if not us.is_browser_connected():
            raise RuntimeError(
                "No browser connected. Open arena.ai with the Tampermonkey userscript installed.\n"
                "See http://localhost:8000/dashboard for instructions."
            )

        # Get fresh reCAPTCHA token
        token = await us.get_fresh_token(timeout=30.0)
        if not token:
            token = ""

        payload = build_payload(model_slug, messages, token)
        logger.info(f"📤 Sending via browser: {model_slug} (uuid={payload['modelAId'][:8]}...)")

        q = await us.request_via_browser(payload, url=STREAM_URL)

        # Stream chunks from queue
        while True:
            try:
                kind, data = await asyncio.wait_for(q.get(), timeout=120.0)
            except asyncio.TimeoutError:
                raise RuntimeError("Request timed out after 120s")

            if kind == "chunk":
                if data:
                    yield data
            elif kind == "done":
                break
            elif kind == "error":
                raise RuntimeError(f"Browser request failed: {data}")


arena_client = ArenaClient()
